# // █▀█ █▀█ █░█░█ █▀▀ █▀█ █▀ ▄▀█ █░█ █▀▀ █▀█
# // █▀▀ █▄█ ▀▄▀▄▀ ██▄ █▀▄ ▄█ █▀█ ▀▄▀ ██▄ █▀▄


$WORKFLOW_ICON=󰛓
$WORKFLOW_DESCRIPTION = Saves power but still looks nice

decoration {
   blur {
        xray = 1
    }
}

misc:vfr = true


layerrule {
	name = workflows_light
	no_anim = true
	match:namespace = ^(rofi|notifications|swaync-(notification-window|control-center)|logout_dialog|waybar)$
}
